name: Generate Daily Digest

on:
  schedule:
    # Run daily at 7:00 AM PST (15:00 UTC during PST, 14:00 UTC during PDT)
    # GitHub Actions uses UTC, so we set it to 15:00 UTC
    # Note: During PDT (March-November), this will be 8:00 AM instead of 7:00 AM
    - cron: '0 15 * * *'

  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  generate-digest:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push to repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for gh-pages

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate digest
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: |
          python main.py

      - name: Check if files changed
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push to main branch
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add index.html archive/ archive.html digest_generation.log
          git commit -m "🤖 Auto-generate daily digest - $(date +'%Y-%m-%d')" || exit 0
          git push

      - name: Deploy to GitHub Pages
        if: steps.check_changes.outputs.changes == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: false
          exclude_assets: '.github,src,*.py,*.md,requirements.txt,config.yaml,*.log'

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Digest generation failed!"
          echo "Check the logs for details."
          # Optional: Add notification to Discord/Slack/Email here
